generatorName: typescript
cleanupOutput: true
inputSpec: http://localhost:8020/api/connections-docs-json
useSingleRequestParameter: true
enumPropertyNaming: 'UPPERCASE'
outputDir: ./src/app/shared/api/generated/connections
additionalProperties:
  supportsES6: true
  